pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
          dir('app') {
              sh 'docker build -t myapp:v2 .'
          }
      }
  }
    stage('Deploy Green') {
      steps {
          dir('app') {
             sh 'kubectl apply -f deployment-green.yaml'
          }
      }
  }
    stage('Switch Traffic') {
      steps {
          dir('app') {
              sh 'kubectl apply -f service.yaml'
          }
      }
    }
  }
}